version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    versioning-strategy: increase
    groups:
      bundler:
        dependency-type: "production"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: increase
    groups:
      npm:
        dependency-type: "development"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      gh-actions:
        update-types:
          - "major"
    schedule:
      interval: "monthly"
